apiVersion: v1
kind: Service
metadata:
  name: macont
  namespace: macont
  labels:
    app: macont
spec:
  type: NodePort
  metadata:
    labels:
      app: macont
  ports:
    - name: grpc
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 8081
      targetPort: 8081
  selector:
    app: macont
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: macont
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - macont
  selector:
    matchLabels:
      app: macont
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: macont
  namespace: macont
spec:
  selector:
    matchLabels:
      app: macont
  replicas: 1
  template:
    metadata:
      labels:
        app: macont
    spec:
      containers:
        - name: macont
          image: registry.brotherlogic-backend.com/brotherlogic/macont:0.10.0 # {"$imagepolicy": "flux-system:macont"}
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred
