// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: macont.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	MacontService_Ping_FullMethodName = "/macont.MacontService/Ping"
)

// MacontServiceClient is the client API for MacontService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MacontServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type macontServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMacontServiceClient(cc grpc.ClientConnInterface) MacontServiceClient {
	return &macontServiceClient{cc}
}

func (c *macontServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MacontService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MacontServiceServer is the server API for MacontService service.
// All implementations should embed UnimplementedMacontServiceServer
// for forward compatibility
type MacontServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

// UnimplementedMacontServiceServer should be embedded to have forward compatible implementations.
type UnimplementedMacontServiceServer struct {
}

func (UnimplementedMacontServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}

// UnsafeMacontServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MacontServiceServer will
// result in compilation errors.
type UnsafeMacontServiceServer interface {
	mustEmbedUnimplementedMacontServiceServer()
}

func RegisterMacontServiceServer(s grpc.ServiceRegistrar, srv MacontServiceServer) {
	s.RegisterService(&MacontService_ServiceDesc, srv)
}

func _MacontService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MacontServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MacontService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MacontServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MacontService_ServiceDesc is the grpc.ServiceDesc for MacontService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MacontService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "macont.MacontService",
	HandlerType: (*MacontServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MacontService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "macont.proto",
}
